[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_solana = "5zTm3fAwh2CXe7HHLT9aRzewm2kM453QQBSmKCaYdM6v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
